CREATE TABLE usuarios (
    id UUID PRIMARY KEY AUTO_GENERATED,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    perfil VARCHAR(20) NOT NULL CHECK (perfil IN ('ADMIN', 'USUARIO', 'GESTOR', 'VISUALIZADOR')),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);