# spring.application.name=backend

# # Configurações do banco de dados


# # Configurações do JPA
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# # Configuração do JWT
# api.security.token.secret=MinhaChaveSuperSecretaComMaisDe32Caracteres